### ISSUE TITLE
pdf.icon doesn't start a new page when the cursor is not on the page 

### ISSUE THREAD

**Issue by selcuktoklucu** [jessedoyle/prawn-icon#49] opened 2020-10-08 16:34 UTC
Thank you so much for this great library! 

I recently realized an issue with adding icons into PDF with prawn and prawn-icon. if the cursor somehow ends up in a negative point, `prawn-icon` doesn't start a new page to continue. So it creates the icon nowhere on the page. I'm not sure if this could be done in this library's scope or users supposed to pay attention to this.

For instance

```
pdf.text "a text after a lot of text", size: 18
pdf.stroke_horizontal_rule
pdf.cursor # => -14.632000000000268
pdf.icon "<icon color="000000">#{some_icon}</icon> #{some_text}", inline_format: true # => nowhere on the page.
pdf.text "more text". # =>  automatically starts a new page, since cursor is not on a page.
pdf.cursor #=> 770.0000000(on a new page)
```

Thank you so much again!

**Comment by jessedoyle** [comment] 2020-10-08 19:09
Hi @selcuktoklucu! Thanks for using `Prawn::Icon`!

I'm just wondering if `Prawn::Icon` should be responsible for modifying the `cursor` position in this case? Wouldn't it make sense for the application that includes `Prawn::Icon` to maintain the cursor position state?

With that being said, your example code does appear to indicate that the `text` method in Prawn core seems to start a new page. I'd like some time investigate the issue further.

If anyone wishes to contribute, feel free to submit a PR and we can work through it.

**Comment by jessedoyle** [comment] 2020-10-08 19:18
@selcuktoklucu - I just wanted to confirm the following line with you:

```ruby
pdf.icon "<icon color="000000">#{some_icon}</icon> #{some_text}"
```

If you're looking to XML-style inline formatting, you must also pass `inline_format: true` to the `#icon` method ([documentation link](https://github.com/jessedoyle/prawn-icon/blob/97c100edfedd9135b3d00f52a6286a2935abf64e/lib/prawn/icon/interface.rb#L61-L62)).

i.e.

```ruby
pdf.icon "<icon color="000000">#{some_icon}</icon> #{some_text}", inline_format: true
```

**Comment by selcuktoklucu** [comment] 2020-10-08 19:47
@jessedoyle  - Thank you for your response!

I'm using the library and it gives the icon correctly in most places. I missed putting `inline_format: true` up in my initial post, that's my mistake.!

The problem was when the method just before the `pdf.icon` moves the cursor out of the page, `pdf.icon` doesn't recognize the cursor is out and creates the icon outside of the page.

My suggestion is adding a method to `pdf.icon` to start a new page in case the cursor is out(e.g cursor has a negative value) or mentioning in the documentation somewhere `pdf.icon` wouldn't start a new page in any case.

If I would have time to dig into the library, I would like to contribute to this awesome library by opening a PR.

**Comment by jessedoyle** [comment] 2020-10-08 20:00
@selcuktoklucu - Got it, thanks!

I think the issue may be that inline-formatted icons use a lower level `Prawn::Text::Formatted::Box` box to layout the content: https://github.com/jessedoyle/prawn-icon/blob/master/lib/prawn/icon/interface.rb#L171-L180

I suspect that's where the fix would go.

**Comment by jessedoyle** [comment] 2020-10-14 01:21
Okay I can reproduce the bug. Here's a minimal reproduction:

```ruby
Prawn::Document.generate('github_issue_49.pdf') do |pdf|
  text = 170.times.map { 'Hello, World!' }.join(' ')
  pdf.text(text, size: 18)
  pdf.icon('Hello, <icon>fas-globe</icon>', inline_format: true, size: 18)
end
```

**Comment by jessedoyle** [comment] 2020-11-11 05:28
Hi @selcuktoklucu! 

I was able to take a deeper look into the issue. It turns out that `Prawn::Icon` made some assumptions with respect to inline icons that affected page-wrapping behaviour. 

Inline-formatted icons used a single `Prawn::Text::Formatted::Box` instance behind the scenes. This is not a correct assumption because transitioning content to a new page may require multiple formatted text boxes.

I've got a fix for this issue in https://github.com/jessedoyle/prawn-icon/pull/50, but it requires a breaking change to the public API.

Essentially we can delegate to the [`formatted_text` method in Prawn core](https://github.com/prawnpdf/prawn/blob/9668b0fcc1b7f08be5c259ec62253b10fc07ccc0/lib/prawn/text.rb#L190-L219) and it'll do a much better job at positioning content correctly. 

My PR modifies inline-formatted icons to do just that, but it means that inline formatted icons are rendered directly to the document as opposed to deferring rendering to a later time. It's a minor change that most people won't notice, but it is technically breaking so it requires a major version bump.

**Closed** 2020-11-11 05:43 UTC
